name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout du code source
      - name: Checkout
        uses: actions/checkout@v3
      
      # Setup et build
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
      
      # Déployer vers un repo séparé contenant uniquement les fichiers build
      - name: Push to deployment repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }}
        with:
          source-directory: 'dist'
          destination-github-username: 't1m4lc'
          destination-repository-name: 'shipwait-script-dist'
          target-branch: main
          user-name: 't1m4lc'
          target-directory: '/'  # Ceci indique de déployer à la racine